# Generated by Django 4.0.3 on 2022-03-25 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purcleapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='user_profile_picture',
            field=models.ImageField(blank=True, default='default.jpg', upload_to='profile_images'),
        ),
    ]
