# Generated by Django 4.0.2 on 2022-04-19 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purcleapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_image',
            field=models.FileField(default='settings.MEDIA_ROOT/images/cursed_turkey.jpg', max_length=254, upload_to='images/'),
        ),
    ]
