# Generated by Django 4.0.2 on 2022-02-13 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purcleapp', '0002_topic_alter_post_post_topic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='topic_id',
            field=models.CharField(max_length=100, primary_key=True, serialize=False, unique=True),
        ),
    ]
