# Generated by Django 4.0.2 on 2022-04-20 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purcleapp', '0003_alter_post_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_image',
            field=models.FileField(default='images/cursed_turkey.jpg', upload_to='images/'),
        ),
    ]
